---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: your-spotify-db
  namespace: your-spotify
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
