---
apiVersion: v1
kind: Service
metadata:
  name: your-spotify-server
  namespace: your-spotify
spec:
  selector:
    app: your-spotify-server
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: your-spotify-client
  namespace: your-spotify
spec:
  selector:
    app: your-spotify-client
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: your-spotify
spec:
  selector:
    app: mongo
  ports:
  - protocol: TCP
    port: 27017
    targetPort: 27017
